### PR TITLE
Smaller font size and margin

### PR DESCRIPTION
**Pull request by alex-mitrevski**
# Summary of changes

This PR reduces the large report margin by 1cm (the margin is still sufficiently large for proper binding) and decreases the default font size from 12pt to 10pt. In addition, the chapter title is shifted a little bit up so that there is a little less blank space on the first chapter page.

# Motivation

In the last few semesters, we've had some very long report submissions, which increases the printing costs for the students. The template settings are partially responsible for this; a few weeks ago, we managed to decrease the length of one report by about 60 pages by tweaking the parameters, while still obtaining a nice printed report. These modified parameters are added with this pull request.

### CODE REVIEW

**Comment by argenos** [comment]
Is the margin still wide enough to make notes? 

While I understand that some of the reports have been on the longer side, I don’t think it’s the norm, should these really be the default settings? Perhaps this merits a discussion on the next staff meeting.

**Comment by argenos** [comment]
GitHub sent me a reminder about this, what should we do about it? My only objection really is the margin, I often use this to make notes during review.

**Comment by alex-mitrevski** [comment]
In my opinion, there's still enough space for taking notes on the margin, but then I mostly my notes on post-its rather than at the margin, so I might be wrong.

Maybe the best is that you take a look at [Ahmed's report](https://pub.h-brs.de/frontdoor/index/index/docId/4828) (we used the settings introduced in this PR there) and see if the margins are enough. If you think then think that keeping the 4cm margin is better, I'll change that back and we can then merge.

**Comment by argenos** [comment]
It looks a bit small. Have you made notes on the pdf with the iPad? I guess zooming in might help, but not much would fit in it. 

What about making them an option that can be passed to the class? A disadvantage might be losing the standard format, but I guess students can anyways modify the class themselves.

**Comment by alex-mitrevski** [comment]
It's fine, we don't have to make it an option. I'll just revert to the 4cm margin. We can tell students to reduce the margin themselves if they have a very long report.

We can keep the other changes though, right?

**Comment by argenos** [comment]
I'll just merge, it should be fine.

**Pull request merged**
